### ISSUE TITLE
Add markdown parsing of answers

### ISSUE THREAD

**Issue by cletusc** [GamerPolls/gamerpolls.com#38]
Limit it to only a few markdown options like links and images. This would allow you to have your own images for answers (like Binding of Isaac characters) and links and stuff.

**Comment by BethaNeeks** [comment]
added markdown parsing to the showPoll function in app/controllers/poll_controller.js

Images and Links are now parsed, using the format:
Image: ![Alt Text](url)
Link: [Text](url)

**Comment by cletusc** [comment]
Commit ref 764198c00141630a757557a4f053e96d67690fe2

@BethaNeeks can you ref the commit sha in your comments or call out the issue number in your commit messages that way everything is all linked up nice and tidy?
